USE testdb

--테이블생성
CREATE TABLE TB_USER
(
	ID VARCHAR(100),
	NAME VARCHAR(100),
	AGE INT,
	JOB VARCHAR(100)
)

--데이터추가
INSERT INTO TB_USER ( ID, NAME, AGE, JOB )
VALUES ( 'U001', '유저', '20', '학생' )

INSERT INTO TB_USER ( ID, NAME, AGE, JOB )
VALUES ( 'U002', '유저', '28', '디자이너' )

INSERT INTO TB_USER ( ID, NAME, AGE, JOB )
VALUES ( 'U003', '유저', '30', '프로그래머' )

INSERT INTO TB_USER ( ID, NAME, AGE, JOB )
VALUES ( 'U004', '유저', '25', '요리사' )

INSERT INTO TB_USER ( ID, NAME, AGE, JOB )
VALUES ( 'U005', '유저', '32', '교사' )

--데이터조회
SELECT
	ID, NAME, AGE, JOB
FROM
	TB_USER WITH(NOLOCK)

--데이터수정
UPDATE
	TB_USER
SET
	NAME = '유저_수정'
WHERE
	ID = 'U001'

--데이터삭제
DELETE FROM TB_USER WHERE ID = 'U006'